
services:

  db:
    container_name: db_et
    image: mysql:8.0
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: logs
    volumes: 
      - ./db:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_et
    image: phpmyadmin:latest
    ports:
      - 8081:80

  api:
    container_name: api_et
    build: ./api
    ports:  # ports for testing purposes, change to expose
      - 8000:80
    depends_on:
      - db
     

  syslog-ng:
    container_name: syslog-ng
    depends_on:
      - db
    build: ./syslog-ng
    ports:
      - 5014:514/udp
      - 6001:601
    volumes:
      - ./logs:/var/log

  algorithms:
    container_name: algorithms_et
    build: ./algorithms
    ports:
      - 5000:5000


volumes:
  db:
